pipeline { 
    agent any 
    stages { 
        stage('clean') { 
            steps { 
                sh 'cd Amazon && mvn clean' 
            } 
        } 
        stage('compile') { 
            steps { 
                sh 'cd Amazon && mvn compile' 
            } 
        } 
        stage('test') { 
            steps { 
                sh 'cd Amazon && mvn test' 
            } 
        } 
    } 
} 

